---
# Source: kube-prometheus-stack/templates/grafana/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-kube-prometheus-grafana
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-grafana
    
    chart: kube-prometheus-stack-13.5.0
    release: "monitoring"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: "monitoring"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: service
    path: "/metrics"
