---
# Source: kube-prometheus-stack/templates/prometheus-operator/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-kube-prometheus-operator
  labels:
    app: kube-prometheus-stack-operator
    
    chart: kube-prometheus-stack-13.5.0
    release: "monitoring"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-kube-prometheus-operator
subjects:
- kind: ServiceAccount
  name: monitoring-kube-prometheus-operator
  namespace: monitoring
