---
# Source: kube-prometheus-stack/templates/prometheus-operator/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-kube-prometheus-operator
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-operator
    
    chart: kube-prometheus-stack-13.5.0
    release: "monitoring"
    heritage: "Helm"
imagePullSecrets:
  []
