---
# Source: kube-prometheus-stack/charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-monitoring-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: monitoring
    chart: prometheus-node-exporter-1.12.0
    jobLabel: node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-monitoring-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: monitoring-prometheus-node-exporter
    namespace: monitoring
