---
# Source: kube-prometheus-stack/templates/alertmanager/psp-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-kube-prometheus-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    
    chart: kube-prometheus-stack-13.5.0
    release: "monitoring"
    heritage: "Helm"
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - monitoring-kube-prometheus-alertmanager
