---
# Source: kube-prometheus-stack/templates/alertmanager/psp-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-kube-prometheus-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    
    chart: kube-prometheus-stack-13.5.0
    release: "monitoring"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-kube-prometheus-alertmanager
subjects:
  - kind: ServiceAccount
    name: monitoring-kube-prometheus-alertmanager
    namespace: monitoring
