name: Kubernetes Demo with GCP Feb 2021 

on:
  push:
    branches:
    - "*"  # run for all branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for all branches
jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
      # matrix:
        # node-version: [10.x]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info

    # RELEASE

    - name: Create VPC
      # if: startsWith(github.ref, 'refs/tags/release-')
      run: gcloud compute networks create demo-vpc-k8s --quiet

    - name: Create Cluster on VPC
      # if: startsWith(github.ref, 'refs/tags/release-')
      run: gcloud container clusters create gcp-demo-cluster --num-nodes 2 --network vpc-k8s --region=europe-west4-a --scopes=storage-rw,compute-ro --quiet --quiet

    # CLEANUP/DELETE

    - name: Delete Cluster
      if: startsWith(github.ref, 'refs/tags/delete-')
      run: gcloud container clusters  delete gcp-demo-cluster --region=europe-west4-a --quiet

    - name: Delete VPC
      if: startsWith(github.ref, 'refs/tags/delete-')
      run: gcloud compute networks delete demo-vpc-k8s --quiet
