name: Kubernetes Demo with GCP Feb 2021 

on:
  push:
    branches:
    - "*"  # run for all branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for all branches
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    # RELEASE

    - name: Create VPC
      if: startsWith(github.ref, 'refs/tags/release-')
      run: gcloud compute networks create demo-vpc-k8s --quiet
      # continue-on-error: true

    - name: Create Cluster on VPC
      if: startsWith(github.ref, 'refs/tags/release-')
      run: gcloud container clusters create gcp-demo-cluster --num-nodes 2 --network demo-vpc-k8s --region=europe-west4-a --scopes=storage-rw,compute-ro --quiet --quiet
      # continue-on-error: true

    # Connect to the cluster with kubectl
    - name: Get Kube Config
      if: startsWith(github.ref, 'refs/tags/release-')
      run: gcloud container clusters get-credentials gcp-demo-cluster --region=europe-west4-a
      
    - name: Applying general kubernetes yaml 
      if: startsWith(github.ref, 'refs/tags/release-')
      run: kubectl apply -f kubernetes/general

    - name: Applying helm kubernetes yaml
      if: startsWith(github.ref, 'refs/tags/release-')
      run: kubectl apply -f kubernetes/helm

    # CLEANUP/DELETE

    - name: Delete Cluster
      if: startsWith(github.ref, 'refs/tags/delete-')
      run: gcloud container clusters  delete gcp-demo-cluster --region=europe-west4-a --quiet

    - name: Delete VPC
      if: startsWith(github.ref, 'refs/tags/delete-')
      run: gcloud compute networks delete demo-vpc-k8s --quiet
